eno=int(input('Enter Employee number:'))
ename=input('Enter Employee name:')
esal=float(input('Enter Employee salary:'))
eaddr=input('Enter Employee Address:')
print('Please confirm the details')
print('Employee number:',eno)
print('Employee name:',ename)
print('Employee salary:',esal)
print('Employee address:',eaddr)
